Feat/IGW-34/42 - 이력서 관리 페이지, 경력﹒소개 작성 페이지 작업
Team-inglo/Giggle-Web pull request #51
Opened 2024-10-25 17:13 UTC by hyeona01

## Related issue 🛠

[//]: # "해당하는 이슈 번호 달아주기"

-  #42 

## Work Description ✏️

[//]: # "작업 내용 간단 소개"

- button 컴포넌트 width : full 로 변경하였습니다.
- 이력서 관리 페이지와 경력 작성/수정 페이지, 소개 작성/수정 페이지 작업하였습니다.
- 다른 이력서 요소들의 작성/수정 페이지의 라우터 구조를 세팅하였습니다.

_이력서 관리 페이지_
![이력서 관리](https://github.com/user-attachments/assets/e67ffe69-140c-4244-9cae-28f3d827b846)

_소개글 작성 및 수정 페이지_
![소개글 수정](https://github.com/user-attachments/assets/2f9f5a0c-f710-4599-8544-33b4cde46a14)

_경력 작성 페이지_
![경력 작성](https://github.com/user-attachments/assets/7d3e3554-e805-4b2d-b21f-b7d38fc3fa32)

_경력 수정 페이지_
![경력 수정](https://github.com/user-attachments/assets/af454ab6-cda0-43f9-a2c4-96fdbbb13af5)

## Uncompleted Tasks 😅

[//]: # "없다면 N/A"

- [ ] 학력 작성/수정 페이지
- [ ] 언어 작성/수정 페이지
- [ ] 북마크 페이지
- [ ] API

## To Reviewers 📢

[//]: # "reviewer가 알면 좋은 내용들"
한번에 PR 하거나 전부 나눠서 PR 하기에는 코드 양이 모호해서
절반 정도 나누어서 PR 합니다!

2024-10-25 18:25 UTC, naarang reviewed
늦은 시간까지 수고많으셨습니다ㅠㅠ!!!🥹

2024-10-25 18:25 UTC, naarang commented on src/components/ManageResume/components/MypageCard.tsx
> +  const renderHeader = () => (
헤더 컴포넌트를 다른 파일로 분리하는 게 더 깔끔할 것 같다는 생각이 듭니다..!!

2024-10-25 18:25 UTC, naarang commented on src/components/WorkExperience/WorkExperiencePost.tsx
> +    const length = textareaRef.current!.value.length;
이거 ! 쓰는 이유가 undefined일 수 있어서 일까요? ! 써두 혹시 예외적인 상황에서 에러 안나겟죠..?

2024-10-25 18:25 UTC, naarang commented on src/hooks/useNavigateBack.ts
> +const useNavigateBack = () => {
오! hook으로 분리하니깐 좋네요ㅎㅎ 저도 사용해보겠습니다~!!👍

2024-10-25 18:25 UTC, naarang commented on src/pages/ManageResumePage/ManageResumePage.tsx
> +      profile_img_url:
아까 제가 받았던 피드백이었는데ㅎㅎ 긴 더미데이터는 constants 폴더로 분리해도 좋을 것 같아용~

2024-10-26 04:59 UTC, MrMirror21 requested changes
고생하셨습니다 👍

2024-10-26 04:59 UTC, MrMirror21 commented on src/components/ManageResume/ResumeEditSection.tsx
> +  // const queryClient = useQueryClient();
지금 저희 프로젝트에서 Tanstack query 사용하실때 queryclient 별도 생성하실 필요 없습니다! 최상위에서 Provider로 제공하고 있고, 토큰까지 authorization에 담은 axios 인스턴스도 미리 만들어서 'api'라는 이름으로 export중입니다.
 /src/api 폴더에 있는 다른 api 통신 함수들 처럼 직성하시고 /src/hook/api 에 있는 커스텀 훅들과 같이 사용하시면 돼요~

2024-10-26 04:59 UTC, MrMirror21 commented on src/components/ManageResume/components/MypageCard.tsx
> +  const renderHeader = () => (
저는 생각이 조금 다른게, 이 파일 자체가 300줄 미만의 소형이기도 하고, 재사용 여지가 없다면 굳이 파일 분리까지는 안해도 될 것 같습니다.
오히려 저는 information은 조건부렌더링이 아닌데도 전부 분리하셨네? 라는 생각이었어요.

2024-10-26 04:59 UTC, MrMirror21 commented on src/components/ManageResume/components/MypageCard.tsx
> +        )}
삼항 연산자를 이중으로 사용하시는건 추후 조건을 알아보기 어려울 수 있어서 다음과 같이 사용해보시는건 어떨까요?
```typescript
type === ManageResumeType.LANGUAGE ?  (
            <BigEditIcon onClick={handleClick} />
          ) : (
            <BlackCtaIcon onClick={handleClick} />
          )
```
지금 보이는 코드상으로는 ManageResumeType을 동시에 여러개 가지고 있는게 아니라면 오직 Language 일 경우에만 cta 버튼을 렌더링하면 되므로 조건식을 간단하게 바꿔볼 수 있을 것 같아요!

2024-10-26 04:59 UTC, MrMirror21 commented on src/components/WorkExperience/WorkExperiencePatch.tsx
> +import Dropdown from '../Common/Dropdown';
절대 경로로 바꿔주세요~ 아무래도 esliint나 config 파일 쪽을 손봐야할 것 같네요. auto import 사용 시에 자꾸 상대 경로로 작성이 되는 것 같은데..

2024-10-26 04:59 UTC, MrMirror21 commented on src/components/WorkExperience/WorkExperiencePatch.tsx
> +  }, [workExperienceData.description]);
textarea의 focus 시에 높이를 자동 조절해주는 코드라고 이해했는데, 맞을까요? 주석으로 설명해주시면 좋을 것 같습니다.

2024-10-26 04:59 UTC, MrMirror21 commented on src/components/WorkExperience/WorkExperiencePost.tsx
> +        </p>
이 부분이 계속 반복되는 것 같은데 별도로 분리하셔도 좋을 것 같습니다.
```typescript
const InputLayout = ({ title, children, isEssential }: InputLayOutProps) => {
  return(
      <div className="w-fit">
        <p className="body-3 text-[#1E1926] px-1 py-2">
          {title}
          <span className="text-[#EE4700] body-1">*</span>
        </p>
        {children}
      </div>
}
```

2024-10-26 05:49 UTC, naarang commented on src/components/ManageResume/components/MypageCard.tsx
> +  const renderHeader = () => (
아하 그런가요? 저는 재사용뿐만 아니라 한 파일이 최대한 컴포넌트는 1개만 가지는 게 좋다고 생각했는데 우준님 말씀 들어보니 그런 것 같네요. 제 의견은 참고만 해주세용ㅎㅎ

2024-10-26 06:11 UTC, hyeona01 commented on src/components/ManageResume/ResumeEditSection.tsx
> +  // const queryClient = useQueryClient();
아하 네네 알겠습니다!!

2024-10-26 06:16 UTC, hyeona01 commented on src/components/ManageResume/components/MypageCard.tsx
> +        )}
ManageResumeType 나머지 타입이 BlackCtaIcon 렌더링이 되어야 해서 이렇게 복잡하게 작성했습니다ㅠㅠ! 가독성이 떨어지니 별도로 렌더링 되는 컴포넌트를 분리하는 방법으로 해보겠습니다!!

2024-10-26 06:23 UTC, hyeona01 commented on src/components/ManageResume/components/MypageCard.tsx
> +  const renderHeader = () => (
조건에 따라서 달리 적용되는 스타일이 많은 컴포넌트라 최종 return 문 코드를 간결하게 가져가고자 파일 내에서 컴포넌트 분리를 많이 했습니다
information 부분은 서버에서 받아오는 데이터 타입과 UI title/body 내용이 다른 구조들과는 달라서 분리하였습니다! 
추후에 information 부분은 다른 파일로 분리해보도록 하겠습니다

2024-10-26 06:26 UTC, hyeona01 commented on src/components/WorkExperience/WorkExperiencePatch.tsx
> +  }, [workExperienceData.description]);
글 작성시, default 로 설정해둔 높이보다 더 길게 작성될 경우, 스크롤이 생기지 않게 자동으로 조절하는 코드입니다! 주석 추가하겠습니다

2024-10-26 06:28 UTC, hyeona01 commented on src/components/WorkExperience/WorkExperiencePost.tsx
> +    const length = textareaRef.current!.value.length;
네 맞습니다! return 문에서 조건부 적용 없이 textarea 태그에 적용되는 ref라서 예외적인 상황은 없습니다

2024-10-26 12:38 UTC, merged